#!/bin/bash

#       lulzsh V 0.1
#      
#       Copyright 2010 Giuseppe D'Inverno <giudinvx[at]gmail[dot]com>
#      
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

function help
{
	echo "Usage:
	$0 [OPTION] \"Your String\"
	
	Application Options:
		-ut, --twitupd \"Some string\"	Update Twitter Account
		-h,  --help	Show this help message and exit"
		exit 0
}

function twitterupd 
{
	msg="$@"
	
	curldem=(`which curl`)
	wgetdem=(`which wget`)
	ncdem=(`which nc`)
	
	if [ `expr length "$msg"` -gt 144 ] 
	then
		echo "Message maximum consent 144 char" 
		exit 0
	elif [ ! -z "$curldem" -a -x "$curldem" ] 
	then
		curl -s -o /dev/null -u ${confvar[0]}:${confvar[1]} -d status="$msg" -d source="lulzsh" http://twitter.com/statuses/update.xml
		exit 0
	elif [ ! -z "$wgetdem" -a -x "$wgetdem" ]
	then
		wget -q -O /dev/null --http-user=${confvar[0]} --http-password=${confvar[1]} --post-data="status=$msg" http://twitter.com:80/statuses/update.xml
		exit 0
	elif [ ! -z "$ncdem" -a -x "$ncdem" ]
	then
		length=(`expr length "$msg" + 21`)
		authb64=(`echo "${confvar[0]}:${confvar[1]}" | base64 | sed 's/=//g'`)
		head="POST http://twitter.com/statuses/update.xml HTTP/1.1\r\nHost: twitter.com\r\nAccept: */*\r\nAuthorization: Basic $authb64\r\nContent-length: $length\r\nContent-type: application/x-www-form-urlencoded\r\nConnection: Close\r\n\r\nstatus=$msg&source=lulzsh"; echo -e $head | nc twitter.com 80
		exit 0
	else
		echo "Please install curl, wget or netcat"
	fi
}
	
if [ ! -f "$HOME/.lulzshconf" ]
then
	for conf in "NAME" "PASSWORD"
do
	echo "$conf"
	read value
	confname="$conf=$value"
	echo "$confname" >> "$HOME/.lulzshconf"
done
exit 0
fi

confvar=(`awk -F "=" '{ print $2 }' "$HOME/.lulzshconf"`)

while [[ $# -gt 0 ]]; do
    case "$1" in
        -ut|--twitupd) twitterupd $2; shift;;
         -h|--help) help; shift;;
         -*|--*) echo "$0: Error - Unknown option $1" 1>&2; exit 1;;
         *) shift;;
    esac
done
